version: "3"

services:
  db:
    image: postgres:14.8-alpine3.18
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass1234
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - todo-api_default

  server:
    build: .
    ports:
      - '3003:3003'
    depends_on:
      - db
    networks:
      - todo-api_default

volumes:
  postgres_data:

networks:
  todo-api_default:
    driver: bridge
